backend:
  name: git-gateway
  branch: main

# uncomment the following line if you want to use the editorial workflow
# publish_mode: editorial_workflow

media_folder: "src/assets/img"
public_folder: "/assets/img"

local_backend: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "publish_date", widget: "datetime"}
      - { label: "Body", name: "body", widget: "markdown"}
  - name: "settings"
    label: "Settings"
    files:
      - name: "metadata"
        label: "Metadata"
        file: "src/_data/site.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - label: "Social Media"
            name: "social"
            widget: object
            collapsed: true
            fields:
              - { label: "Twitter handle", name: "twitter", widget: "string" }
              - { label: "Social media image", name: "image", widget: "image" }
              - { label: "Allow Pinterest pins", name: "pinterest_allow_pin", widget: "boolean" }



      


